# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug_m68k-amigaos
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug_m68k-amigaos)
  CC         = m68k-amigaos-gcc
  CXX        = m68k-amigaos-g++
  AR         = m68k-amigaos-ar
  OBJDIR     = obj/m68k-amigaos/Debug/compression
  TARGETDIR  = lib
  TARGET     = $(TARGETDIR)/libcompression_d.a
  DEFINES   += -D__AMIGA__ -DHAVE_CONFIG_H -DMILKYTRACKER -D__THREADTIMER__ -DDRIVER_UNIX -DDEBUG
  INCLUDES  += -I. -Isrc/fx -Isrc/tracker -Isrc/compression -Isrc/milkyplay -Isrc/milkyplay/drivers/generic -Isrc/ppui -Isrc/ppui/sdl -Isrc/ppui/osinterface -Isrc/ppui/osinterface/posix -Isrc/milkyplay/drivers/jack -I../../src/milkyplay/drivers/sdl -I/opt/m68k-amigaos/include/SDL -I/opt/m68k-amigaos/include -Isrc/compression -Isrc/compression/lha -Isrc/compression/zlib -Isrc/compression/zziplib
  CPPFLAGS  +=  -m68020 -noixemul -fpermissive -fomit-frame-pointer  $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L/opt/m68k-amigaos/lib -L/opt/m68k-amigaos/m68k-amigaos/lib
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release_m68k-amigaos)
  CC         = m68k-amigaos-gcc
  CXX        = m68k-amigaos-g++
  AR         = m68k-amigaos-ar
  OBJDIR     = obj/m68k-amigaos/Release/compression
  TARGETDIR  = lib
  TARGET     = $(TARGETDIR)/libcompression.a
  DEFINES   += -D__AMIGA__ -DHAVE_CONFIG_H -DMILKYTRACKER -D__THREADTIMER__ -DDRIVER_UNIX -DNDEBUG
  INCLUDES  += -I. -Isrc/fx -Isrc/tracker -Isrc/compression -Isrc/milkyplay -Isrc/milkyplay/drivers/generic -Isrc/ppui -Isrc/ppui/sdl -Isrc/ppui/osinterface -Isrc/ppui/osinterface/posix -Isrc/milkyplay/drivers/jack -I../../src/milkyplay/drivers/sdl -I/opt/m68k-amigaos/include/SDL -I/opt/m68k-amigaos/include -Isrc/compression -Isrc/compression/lha -Isrc/compression/zlib -Isrc/compression/zziplib
  CPPFLAGS  +=  -m68020 -noixemul -fpermissive -fomit-frame-pointer  $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -L/opt/m68k-amigaos/lib -L/opt/m68k-amigaos/m68k-amigaos/lib
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking compression
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning compression
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif


-include $(OBJECTS:%.o=%.d)
