# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug_m68k-amigaos
endif
export config

PROJECTS := milkyplay fx compression ppui milkytracker

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

milkyplay: 
	@echo "==== Building milkyplay ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f milkyplay.make

fx: 
	@echo "==== Building fx ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f fx.make

compression: 
	@echo "==== Building compression ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f compression.make

ppui: 
	@echo "==== Building ppui ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f ppui.make

milkytracker: ppui milkyplay compression fx
	@echo "==== Building milkytracker ($(config)) ===="
	@${MAKE} --no-print-directory -C projects -f Makefile

clean:
	@${MAKE} --no-print-directory -C . -f milkyplay.make clean
	@${MAKE} --no-print-directory -C . -f fx.make clean
	@${MAKE} --no-print-directory -C . -f compression.make clean
	@${MAKE} --no-print-directory -C . -f ppui.make clean
	@${MAKE} --no-print-directory -C projects -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug_m68k-amigaos"
	@echo "   release_m68k-amigaos"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   milkyplay"
	@echo "   fx"
	@echo "   compression"
	@echo "   ppui"
	@echo "   milkytracker"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
