# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug_m68k-amigaos
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug_m68k-amigaos)
  CC         = m68k-amigaos-gcc
  CXX        = m68k-amigaos-g++
  AR         = m68k-amigaos-ar
  OBJDIR     = obj/m68k-amigaos/Debug/milkyplay
  TARGETDIR  = lib
  TARGET     = $(TARGETDIR)/libmilkyplay_d.a
  DEFINES   += -D__AMIGA__ -DHAVE_CONFIG_H -DMILKYTRACKER -D__THREADTIMER__ -DDRIVER_UNIX -DDEBUG
  INCLUDES  += -I. -Isrc/fx -Isrc/tracker -Isrc/compression -Isrc/milkyplay -Isrc/milkyplay/drivers/generic -Isrc/ppui -Isrc/ppui/sdl -Isrc/ppui/osinterface -Isrc/ppui/osinterface/posix -Isrc/milkyplay/drivers/jack -I../../src/milkyplay/drivers/sdl -I/opt/m68k-amigaos/include/SDL -I/opt/m68k-amigaos/include -Isrc/milkyplay -Isrc/milkyplay/drivers/sdl
  CPPFLAGS  +=  -m68020 -noixemul -fpermissive -fomit-frame-pointer  $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L/opt/m68k-amigaos/lib -L/opt/m68k-amigaos/m68k-amigaos/lib
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release_m68k-amigaos)
  CC         = m68k-amigaos-gcc
  CXX        = m68k-amigaos-g++
  AR         = m68k-amigaos-ar
  OBJDIR     = obj/m68k-amigaos/Release/milkyplay
  TARGETDIR  = lib
  TARGET     = $(TARGETDIR)/libmilkyplay.a
  DEFINES   += -D__AMIGA__ -DHAVE_CONFIG_H -DMILKYTRACKER -D__THREADTIMER__ -DDRIVER_UNIX -DNDEBUG
  INCLUDES  += -I. -Isrc/fx -Isrc/tracker -Isrc/compression -Isrc/milkyplay -Isrc/milkyplay/drivers/generic -Isrc/ppui -Isrc/ppui/sdl -Isrc/ppui/osinterface -Isrc/ppui/osinterface/posix -Isrc/milkyplay/drivers/jack -I../../src/milkyplay/drivers/sdl -I/opt/m68k-amigaos/include/SDL -I/opt/m68k-amigaos/include -Isrc/milkyplay -Isrc/milkyplay/drivers/sdl
  CPPFLAGS  +=  -m68020 -noixemul -fpermissive -fomit-frame-pointer  $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -L/opt/m68k-amigaos/lib -L/opt/m68k-amigaos/m68k-amigaos/lib
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/LoaderMDL.o \
	$(OBJDIR)/LoaderFAR.o \
	$(OBJDIR)/LoaderPLM.o \
	$(OBJDIR)/SampleLoaderWAV.o \
	$(OBJDIR)/LoaderCBA.o \
	$(OBJDIR)/ExporterXM.o \
	$(OBJDIR)/LoaderDTM.o \
	$(OBJDIR)/LittleEndian.o \
	$(OBJDIR)/LoaderMOD.o \
	$(OBJDIR)/XModule.o \
	$(OBJDIR)/Loader669.o \
	$(OBJDIR)/AudioDriverBase.o \
	$(OBJDIR)/LoaderDSM.o \
	$(OBJDIR)/LoaderS3M.o \
	$(OBJDIR)/MasterMixer.o \
	$(OBJDIR)/SampleLoaderGeneric.o \
	$(OBJDIR)/XMFile.o \
	$(OBJDIR)/PlayerBase.o \
	$(OBJDIR)/LoaderOKT.o \
	$(OBJDIR)/LoaderIT.o \
	$(OBJDIR)/AudioDriver_WAVWriter.o \
	$(OBJDIR)/PlayerFAR.o \
	$(OBJDIR)/PlayerSTD.o \
	$(OBJDIR)/LoaderIMF.o \
	$(OBJDIR)/ResamplerFactory.o \
	$(OBJDIR)/LoaderDIGI.o \
	$(OBJDIR)/LoaderGDM.o \
	$(OBJDIR)/SampleLoaderAbstract.o \
	$(OBJDIR)/AudioDriverManager.o \
	$(OBJDIR)/PlayerIT.o \
	$(OBJDIR)/LoaderPTM.o \
	$(OBJDIR)/LoaderDBM.o \
	$(OBJDIR)/AudioDriver_NULL.o \
	$(OBJDIR)/LoaderAMS.o \
	$(OBJDIR)/LoaderUNI.o \
	$(OBJDIR)/LoaderAMF.o \
	$(OBJDIR)/LoaderXM.o \
	$(OBJDIR)/ChannelMixer.o \
	$(OBJDIR)/LoaderULT.o \
	$(OBJDIR)/LoaderMTM.o \
	$(OBJDIR)/XIInstrument.o \
	$(OBJDIR)/LoaderPSM.o \
	$(OBJDIR)/PlayerGeneric.o \
	$(OBJDIR)/SampleLoaderIFF.o \
	$(OBJDIR)/LoaderSTM.o \
	$(OBJDIR)/LoaderMXM.o \
	$(OBJDIR)/SampleLoaderAIFF.o \
	$(OBJDIR)/SampleLoaderALL.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking milkyplay
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning milkyplay
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/LoaderMDL.o: src/milkyplay/LoaderMDL.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderFAR.o: src/milkyplay/LoaderFAR.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderPLM.o: src/milkyplay/LoaderPLM.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SampleLoaderWAV.o: src/milkyplay/SampleLoaderWAV.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderCBA.o: src/milkyplay/LoaderCBA.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ExporterXM.o: src/milkyplay/ExporterXM.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderDTM.o: src/milkyplay/LoaderDTM.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LittleEndian.o: src/milkyplay/LittleEndian.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderMOD.o: src/milkyplay/LoaderMOD.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/XModule.o: src/milkyplay/XModule.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Loader669.o: src/milkyplay/Loader669.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AudioDriverBase.o: src/milkyplay/AudioDriverBase.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderDSM.o: src/milkyplay/LoaderDSM.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderS3M.o: src/milkyplay/LoaderS3M.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MasterMixer.o: src/milkyplay/MasterMixer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SampleLoaderGeneric.o: src/milkyplay/SampleLoaderGeneric.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/XMFile.o: src/milkyplay/XMFile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PlayerBase.o: src/milkyplay/PlayerBase.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderOKT.o: src/milkyplay/LoaderOKT.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderIT.o: src/milkyplay/LoaderIT.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AudioDriver_WAVWriter.o: src/milkyplay/AudioDriver_WAVWriter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PlayerFAR.o: src/milkyplay/PlayerFAR.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PlayerSTD.o: src/milkyplay/PlayerSTD.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderIMF.o: src/milkyplay/LoaderIMF.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ResamplerFactory.o: src/milkyplay/ResamplerFactory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderDIGI.o: src/milkyplay/LoaderDIGI.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderGDM.o: src/milkyplay/LoaderGDM.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SampleLoaderAbstract.o: src/milkyplay/SampleLoaderAbstract.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AudioDriverManager.o: src/milkyplay/AudioDriverManager.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PlayerIT.o: src/milkyplay/PlayerIT.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderPTM.o: src/milkyplay/LoaderPTM.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderDBM.o: src/milkyplay/LoaderDBM.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AudioDriver_NULL.o: src/milkyplay/AudioDriver_NULL.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderAMS.o: src/milkyplay/LoaderAMS.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderUNI.o: src/milkyplay/LoaderUNI.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderAMF.o: src/milkyplay/LoaderAMF.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderXM.o: src/milkyplay/LoaderXM.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ChannelMixer.o: src/milkyplay/ChannelMixer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderULT.o: src/milkyplay/LoaderULT.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderMTM.o: src/milkyplay/LoaderMTM.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/XIInstrument.o: src/milkyplay/XIInstrument.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderPSM.o: src/milkyplay/LoaderPSM.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PlayerGeneric.o: src/milkyplay/PlayerGeneric.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SampleLoaderIFF.o: src/milkyplay/SampleLoaderIFF.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderSTM.o: src/milkyplay/LoaderSTM.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LoaderMXM.o: src/milkyplay/LoaderMXM.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SampleLoaderAIFF.o: src/milkyplay/SampleLoaderAIFF.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SampleLoaderALL.o: src/milkyplay/SampleLoaderALL.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
