# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug_m68k-amigaos
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug_m68k-amigaos)
  CC         = m68k-amigaos-gcc
  CXX        = m68k-amigaos-g++
  AR         = m68k-amigaos-ar
  OBJDIR     = obj/m68k-amigaos/Debug/ppui
  TARGETDIR  = lib
  TARGET     = $(TARGETDIR)/libppui_d.a
  DEFINES   += -D__AMIGA__ -DHAVE_CONFIG_H -DMILKYTRACKER -D__THREADTIMER__ -DDRIVER_UNIX -DDEBUG
  INCLUDES  += -I. -Isrc/fx -Isrc/tracker -Isrc/compression -Isrc/milkyplay -Isrc/milkyplay/drivers/generic -Isrc/ppui -Isrc/ppui/sdl -Isrc/ppui/osinterface -Isrc/ppui/osinterface/posix -Isrc/milkyplay/drivers/jack -I../../src/milkyplay/drivers/sdl -I/opt/m68k-amigaos/include/SDL -I/opt/m68k-amigaos/include -Isrc/ppui/osinterface/posix -Isrc/ppui -Isrc/ppui/osinterface -Isrc/ppui/sdl
  CPPFLAGS  +=  -m68020 -noixemul -fpermissive -fomit-frame-pointer  $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L/opt/m68k-amigaos/lib -L/opt/m68k-amigaos/m68k-amigaos/lib
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release_m68k-amigaos)
  CC         = m68k-amigaos-gcc
  CXX        = m68k-amigaos-g++
  AR         = m68k-amigaos-ar
  OBJDIR     = obj/m68k-amigaos/Release/ppui
  TARGETDIR  = lib
  TARGET     = $(TARGETDIR)/libppui.a
  DEFINES   += -D__AMIGA__ -DHAVE_CONFIG_H -DMILKYTRACKER -D__THREADTIMER__ -DDRIVER_UNIX -DNDEBUG
  INCLUDES  += -I. -Isrc/fx -Isrc/tracker -Isrc/compression -Isrc/milkyplay -Isrc/milkyplay/drivers/generic -Isrc/ppui -Isrc/ppui/sdl -Isrc/ppui/osinterface -Isrc/ppui/osinterface/posix -Isrc/milkyplay/drivers/jack -I../../src/milkyplay/drivers/sdl -I/opt/m68k-amigaos/include/SDL -I/opt/m68k-amigaos/include -Isrc/ppui/osinterface/posix -Isrc/ppui -Isrc/ppui/osinterface -Isrc/ppui/sdl
  CPPFLAGS  +=  -m68020 -noixemul -fpermissive -fomit-frame-pointer  $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -L/opt/m68k-amigaos/lib -L/opt/m68k-amigaos/m68k-amigaos/lib
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/Graphics_16BIT.o \
	$(OBJDIR)/PPUIConfig.o \
	$(OBJDIR)/DictionaryKey.o \
	$(OBJDIR)/Control.o \
	$(OBJDIR)/Graphics_15BIT.o \
	$(OBJDIR)/DialogFileSelector.o \
	$(OBJDIR)/KeyboardBindingHandler.o \
	$(OBJDIR)/ListBoxFileBrowser.o \
	$(OBJDIR)/Graphics_BGR24_SLOW.o \
	$(OBJDIR)/Graphics_OGL.o \
	$(OBJDIR)/MessageBoxContainer.o \
	$(OBJDIR)/Dictionary.o \
	$(OBJDIR)/StaticText.o \
	$(OBJDIR)/RadioGroup.o \
	$(OBJDIR)/Button.o \
	$(OBJDIR)/ListBox.o \
	$(OBJDIR)/Seperator.o \
	$(OBJDIR)/Menu.o \
	$(OBJDIR)/Graphics_32bpp_generic.o \
	$(OBJDIR)/Graphics_BGR24.o \
	$(OBJDIR)/Slider.o \
	$(OBJDIR)/Graphics_24bpp_generic.o \
	$(OBJDIR)/DialogBase.o \
	$(OBJDIR)/Graphics_ARGB32.o \
	$(OBJDIR)/Container.o \
	$(OBJDIR)/Event.o \
	$(OBJDIR)/Scrollbar.o \
	$(OBJDIR)/Tools.o \
	$(OBJDIR)/Screen.o \
	$(OBJDIR)/Font.o \
	$(OBJDIR)/ContextMenu.o \
	$(OBJDIR)/TransparentContainer.o \
	$(OBJDIR)/CheckBox.o \
	$(OBJDIR)/PPPathFactory.o \
	$(OBJDIR)/DisplayDeviceFB_SDL.o \
	$(OBJDIR)/DisplayDeviceOGL_SDL.o \
	$(OBJDIR)/DisplayDevice_SDL.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking ppui
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning ppui
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/Graphics_16BIT.o: src/ppui/Graphics_16BIT.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PPUIConfig.o: src/ppui/PPUIConfig.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DictionaryKey.o: src/ppui/DictionaryKey.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Control.o: src/ppui/Control.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Graphics_15BIT.o: src/ppui/Graphics_15BIT.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DialogFileSelector.o: src/ppui/DialogFileSelector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/KeyboardBindingHandler.o: src/ppui/KeyboardBindingHandler.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ListBoxFileBrowser.o: src/ppui/ListBoxFileBrowser.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Graphics_BGR24_SLOW.o: src/ppui/Graphics_BGR24_SLOW.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Graphics_OGL.o: src/ppui/Graphics_OGL.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MessageBoxContainer.o: src/ppui/MessageBoxContainer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Dictionary.o: src/ppui/Dictionary.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StaticText.o: src/ppui/StaticText.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RadioGroup.o: src/ppui/RadioGroup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Button.o: src/ppui/Button.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ListBox.o: src/ppui/ListBox.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Seperator.o: src/ppui/Seperator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Menu.o: src/ppui/Menu.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Graphics_32bpp_generic.o: src/ppui/Graphics_32bpp_generic.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Graphics_BGR24.o: src/ppui/Graphics_BGR24.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Slider.o: src/ppui/Slider.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Graphics_24bpp_generic.o: src/ppui/Graphics_24bpp_generic.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DialogBase.o: src/ppui/DialogBase.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Graphics_ARGB32.o: src/ppui/Graphics_ARGB32.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Container.o: src/ppui/Container.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Event.o: src/ppui/Event.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Scrollbar.o: src/ppui/Scrollbar.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Tools.o: src/ppui/Tools.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Screen.o: src/ppui/Screen.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Font.o: src/ppui/Font.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ContextMenu.o: src/ppui/ContextMenu.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TransparentContainer.o: src/ppui/TransparentContainer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CheckBox.o: src/ppui/CheckBox.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PPPathFactory.o: src/ppui/osinterface/PPPathFactory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DisplayDeviceFB_SDL.o: src/ppui/sdl/DisplayDeviceFB_SDL.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DisplayDeviceOGL_SDL.o: src/ppui/sdl/DisplayDeviceOGL_SDL.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DisplayDevice_SDL.o: src/ppui/sdl/DisplayDevice_SDL.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
