/*
 *  tracker/ControlIDs.h
 *
 *  Copyright 2008 Peter Barth
 *
 *  This file is part of Milkytracker.
 *
 *  Milkytracker is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Milkytracker is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Milkytracker.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#ifndef CONTROLLIDS__H
#define CONTROLLIDS__H

#ifndef __LOWRES__
/*#define MAINMENU_PLAY_SONG		(BUTTON_MENU_ITEM_0+0)
#define MAINMENU_PLAY_PATTERN	(BUTTON_MENU_ITEM_0+1)
#define MAINMENU_STOP			(BUTTON_MENU_ITEM_0+2)
#define MAINMENU_ZAP			(BUTTON_MENU_ITEM_0+3)
#define MAINMENU_LOAD			(BUTTON_MENU_ITEM_0+4)
#define MAINMENU_SAVE			(BUTTON_MENU_ITEM_0+5)
#define MAINMENU_INSEDIT		(BUTTON_MENU_ITEM_0+8)
#define MAINMENU_SMPEDIT		(BUTTON_MENU_ITEM_0+9)
#define MAINMENU_ADVEDIT		(BUTTON_MENU_ITEM_0+10)
#define MAINMENU_TRANSPOSE		(BUTTON_MENU_ITEM_0+11)
#define MAINMENU_CONFIG			(BUTTON_MENU_ITEM_0+14)*/
#define MAINMENU_PLAY_SONG		(BUTTON_MENU_ITEM_0+12)
#define MAINMENU_PLAY_PATTERN	(BUTTON_MENU_ITEM_0+13)
#define MAINMENU_STOP			(BUTTON_MENU_ITEM_0+14)
#define MAINMENU_ZAP			(BUTTON_MENU_ITEM_0+0)
#define MAINMENU_LOAD			(BUTTON_MENU_ITEM_0+1)
#define MAINMENU_SAVE			(BUTTON_MENU_ITEM_0+2)
#define MAINMENU_DISKMENU		(BUTTON_MENU_ITEM_0+3)
#define MAINMENU_INSEDIT		(BUTTON_MENU_ITEM_0+5)
#define MAINMENU_SMPEDIT		(BUTTON_MENU_ITEM_0+4)
#define MAINMENU_ADVEDIT		(BUTTON_MENU_ITEM_0+6)
#define MAINMENU_TRANSPOSE		(BUTTON_MENU_ITEM_0+7)
#define MAINMENU_ABOUT			(BUTTON_MENU_ITEM_0+8)
#define MAINMENU_OPTIMIZE		(BUTTON_MENU_ITEM_0+9)
#define MAINMENU_QUICKOPTIONS	(BUTTON_MENU_ITEM_0+10)
#define MAINMENU_CONFIG			(BUTTON_MENU_ITEM_0+11)
#define MAINMENU_PLAY_POSITION	(BUTTON_MENU_ITEM_0+20)
#define MAINMENU_SAVEAS			(BUTTON_MENU_ITEM_0+21)
#define MAINMENU_EDIT			(BUTTON_MENU_ITEM_0+22)
#else
#define MAINMENU_PLAY_SONG		(BUTTON_MENU_ITEM_0+12)
#define MAINMENU_PLAY_PATTERN	(BUTTON_MENU_ITEM_0+13)
#define MAINMENU_STOP			(BUTTON_MENU_ITEM_0+14)
#define MAINMENU_ZAP			(BUTTON_MENU_ITEM_0+0)
#define MAINMENU_LOAD			(BUTTON_MENU_ITEM_0+1)
#define MAINMENU_SAVE			(BUTTON_MENU_ITEM_0+2)
#define MAINMENU_DISKMENU		(BUTTON_MENU_ITEM_0+3)
#define MAINMENU_INSEDIT		(BUTTON_MENU_ITEM_0+5)
#define MAINMENU_SMPEDIT		(BUTTON_MENU_ITEM_0+4)
#define MAINMENU_ADVEDIT		(BUTTON_MENU_ITEM_0+6)
#define MAINMENU_TRANSPOSE		(BUTTON_MENU_ITEM_0+7)
#define MAINMENU_ABOUT			(BUTTON_MENU_ITEM_0+8)
#define MAINMENU_OPTIMIZE		(BUTTON_MENU_ITEM_0+9)
#define MAINMENU_QUICKOPTIONS	(BUTTON_MENU_ITEM_0+10)
#define MAINMENU_CONFIG			(BUTTON_MENU_ITEM_0+11)
#define MAINMENU_PLAY_POSITION	(BUTTON_MENU_ITEM_0+20)
#define MAINMENU_SAVEAS			(BUTTON_MENU_ITEM_0+21)
#define MAINMENU_EDIT			(BUTTON_MENU_ITEM_0+22)
#endif

#define BUTTON_0							100
#define BUTTON_1							101
#define BUTTON_2							102
#define BUTTON_3							103
#define BUTTON_4							104
#define BUTTON_5							105
#define BUTTON_6							106
#define BUTTON_APP_EXIT						110
#define CONTAINER_SCOPECONTROL				65536
#define BUTTON_SCOPECONTROL_MUTE			(65536+1)
#define BUTTON_SCOPECONTROL_SOLO			(65536+2)
#define BUTTON_SCOPECONTROL_REC				(65536+3)

// orderlist control
#define BUTTON_ORDERLIST_INSERT				180
#define BUTTON_ORDERLIST_NEXT				181
#define BUTTON_ORDERLIST_PREVIOUS			182
#define BUTTON_ORDERLIST_DELETE				184
#define BUTTON_ORDERLIST_SONGLENGTH_PLUS	185
#define BUTTON_ORDERLIST_SONGLENGTH_MINUS	186
#define BUTTON_ORDERLIST_REPEAT_PLUS		187
#define BUTTON_ORDERLIST_REPEAT_MINUS		188
#define BUTTON_ORDERLIST_EXTENT				189
#define BUTTON_ORDERLIST_SEQENTRY			190
#define BUTTON_ORDERLIST_CLNENTRY			191

#define BUTTON_JAMMENU_NEXTORDERLIST		200
#define BUTTON_JAMMENU_PREVORDERLIST		201
#define STATICTEXT_JAMMENU_CURORDER			202
#define STATICTEXT_JAMMENU_CURPATTERN		203
#define BUTTON_JAMMENU_NEXTINSTRUMENT		204
#define BUTTON_JAMMENU_PREVINSTRUMENT		205
#define STATICTEXT_JAMMENU_CURINSTRUMENT	206
#define BUTTON_JAMMENU_TOGGLEPIANOSIZE		207

#define STATICTEXT_ORDERLIST_SONGLENGTH		10200
#define STATICTEXT_ORDERLIST_REPEAT    		10201

// speed control
#define BUTTON_BPM_PLUS						210
#define BUTTON_BPM_MINUS					211
#define BUTTON_SPEED_PLUS					212
#define BUTTON_SPEED_MINUS					213
#define BUTTON_ADD_PLUS						214
#define BUTTON_ADD_MINUS					215
#define BUTTON_OCTAVE_PLUS					216
#define BUTTON_OCTAVE_MINUS					217
#define BUTTON_SPEEDCONTAINERFLIP			218

#define STATICTEXT_SPEED_BPM_DESC			10300
#define STATICTEXT_SPEED_SPEED_DESC  		10301
#define STATICTEXT_SPEED_PATTERNADD_DESC	10302
#define STATICTEXT_SPEED_OCTAVE_DESC		10303
#define STATICTEXT_SPEED_MAINVOL_DESC		10304
#define STATICTEXT_SPEED_BPM				10305
#define STATICTEXT_SPEED_SPEED    			10306
#define STATICTEXT_SPEED_PATTERNADD			10307
#define STATICTEXT_SPEED_OCTAVE				10308
#define STATICTEXT_SPEED_MAINVOL			10309

// pattern control
#define BUTTON_PATTERN_PLUS					220
#define BUTTON_PATTERN_MINUS				221
#define BUTTON_PATTERN_SIZE_PLUS			222
#define BUTTON_PATTERN_SIZE_MINUS			223
#define BUTTON_PATTERN_EXPAND				224
#define BUTTON_PATTERN_SHRINK				225

#define STATICTEXT_PATTERN_INDEX			10400
#define STATICTEXT_PATTERN_LENGTH    		10401

// instrument/samples listboxes
#define STATICTEXT_INSTRUMENTS_ALTERNATIVEHEADER	226
#define STATICTEXT_INSTRUMENTS_ALTERNATIVEHEADER2	227
#define BUTTON_INSTRUMENTS_FLIP				228
#define BUTTON_INSTRUMENT					229
#define BUTTON_INSTRUMENTS_PLUS				230
#define BUTTON_INSTRUMENTS_MINUS			231
#define BUTTON_SAMPLES_PLUS					232
#define BUTTON_SAMPLES_MINUS				233
#define BUTTON_PIANO_EDIT					234
#define BUTTON_PIANO_PLAY					235
#define STATICTEXT_SAMPLEHEADER				492
#define BUTTON_SAMPLES_INVOKEHDRECORDER		493

// envelope/instrument editor
#define BUTTON_ENVELOPE_UNDO				236
#define BUTTON_ENVELOPE_REDO				237
#define BUTTON_ENVELOPE_COPY				238
#define BUTTON_ENVELOPE_PASTE				239
#define BUTTON_ENVELOPE_ADD					240
#define BUTTON_ENVELOPE_DELETE				241
#define BUTTON_ENVELOPE_SUSTAIN_PLUS		242
#define BUTTON_ENVELOPE_SUSTAIN_MINUS		243
#define BUTTON_ENVELOPE_LOOPSTART_PLUS		244
#define BUTTON_ENVELOPE_LOOPSTART_MINUS		245
#define BUTTON_ENVELOPE_LOOPEND_PLUS		246
#define BUTTON_ENVELOPE_LOOPEND_MINUS		247
#define BUTTON_ENVELOPE_VOLUME				248
#define BUTTON_ENVELOPE_PANNING				249
#define BUTTON_ENVELOPE_PREDEF_STORE		699
#define BUTTON_ENVELOPE_PREDEF_0			700
#define BUTTON_ENVELOPE_PREDEF_1			701
#define BUTTON_ENVELOPE_PREDEF_2			702
#define BUTTON_ENVELOPE_PREDEF_3			703
#define BUTTON_ENVELOPE_PREDEF_4			704
#define BUTTON_ENVELOPE_PREDEF_5			705
#define BUTTON_ENVELOPE_PREDEF_6			706
#define BUTTON_ENVELOPE_PREDEF_7			707
#define BUTTON_ENVELOPE_PREDEF_8			708
#define BUTTON_ENVELOPE_PREDEF_9			709
#define BUTTON_ENVELOPE_SCALEX				750
#define BUTTON_ENVELOPE_SCALEY				751
#define BUTTON_ENVELOPE_ZOOMIN				760
#define BUTTON_ENVELOPE_ZOOMOUT				761
#define BUTTON_ENVELOPE_ZOOMDEFAULT			762

#define CHECKBOX_ENVELOPE_ON				250
#define CHECKBOX_ENVELOPE_SUSTAIN			251
#define CHECKBOX_ENVELOPE_LOOP				252

#define SLIDER_SAMPLE_VOLUME				253
#define SLIDER_SAMPLE_PANNING				254
#define SLIDER_SAMPLE_FINETUNE				255

#define BUTTON_SAMPLE_RELNOTENUM_OCTUP		256
#define BUTTON_SAMPLE_RELNOTENUM_OCTDN		257
#define BUTTON_SAMPLE_RELNOTENUM_NOTEUP		258
#define BUTTON_SAMPLE_RELNOTENUM_NOTEDN		259

#define SLIDER_SAMPLE_VOLFADE 				260
#define SLIDER_SAMPLE_VIBSPEED 				261
#define SLIDER_SAMPLE_VIBDEPTH 				262
#define SLIDER_SAMPLE_VIBSWEEP 				263
#define RADIOGROUP_SAMPLE_VIBTYPE			264

#define BUTTON_INSTRUMENTEDITOR_EXIT		265
#define BUTTON_INSTRUMENTEDITOR_LOAD		266
#define BUTTON_INSTRUMENTEDITOR_SAVE		267

#define BUTTON_INSTRUMENTEDITOR_COPY		268
#define BUTTON_INSTRUMENTEDITOR_SWAP		269
#define BUTTON_INSTRUMENTEDITOR_CLEAR		270

// sample editor
#define BUTTON_SAMPLE_PLAY_STOP				280
#define BUTTON_SAMPLE_PLAY_UP				281
#define BUTTON_SAMPLE_PLAY_DOWN				282
#define BUTTON_SAMPLE_PLAY_WAVE				283
#define BUTTON_SAMPLE_PLAY_RANGE			284
#define BUTTON_SAMPLE_PLAY_DISPLAY			285

#define BUTTON_SAMPLE_RANGE_SHOW			286
#define BUTTON_SAMPLE_RANGE_ALL				287
#define BUTTON_SAMPLE_RANGE_CLEAR			288
#define BUTTON_SAMPLE_RANGE_ZOOMOUT			289
#define BUTTON_SAMPLE_RANGE_SHOWALL			290
//#define BUTTON_SAMPLE_RANGE_SAVE			291
#define BUTTON_SAMPLE_APPLY_LASTFILTER		291

#define BUTTON_SAMPLE_EDIT_CUT				292
#define BUTTON_SAMPLE_EDIT_COPY				293
#define BUTTON_SAMPLE_EDIT_PASTE			294

#define BUTTON_SAMPLE_EDIT_CROP				295
#define BUTTON_SAMPLE_EDIT_VOL				296
#define BUTTON_SAMPLE_EDIT_DRAW				297

#define RADIOGROUP_SAMPLE_LOOPTYPE			298
#define RADIOGROUP_SAMPLE_RESTYPE			299

#define BUTTON_SAMPLEEDITOR_EXIT			300

#define BUTTON_SAMPLE_LOAD					301
#define BUTTON_SAMPLE_SAVE					302

#define BUTTON_SAMPLE_EDIT_CLEAR			303
#define BUTTON_SAMPLE_EDIT_MINIMISE			304
#define BUTTON_SAMPLE_EDIT_REPSTARTPLUS		305
#define BUTTON_SAMPLE_EDIT_REPSTARTMINUS	306
#define BUTTON_SAMPLE_EDIT_REPLENPLUS		307
#define BUTTON_SAMPLE_EDIT_REPLENMINUS		308

#define BUTTON_SAMPLE_UNDO					310
#define BUTTON_SAMPLE_REDO					311

#define BUTTON_SAMPLE_ZOOM_PLUS				312
#define BUTTON_SAMPLE_ZOOM_MINUS			313

#define CHECKBOX_SAMPLE_ONESHOT				314

// INPUT CONTROL
#define INPUT_BUTTON_0						400
#define INPUT_BUTTON_1						401
#define INPUT_BUTTON_2						402
#define INPUT_BUTTON_3						403
#define INPUT_BUTTON_4						404
#define INPUT_BUTTON_5						405
#define INPUT_BUTTON_6						406
#define INPUT_BUTTON_7						407
#define INPUT_BUTTON_8						408
#define INPUT_BUTTON_9						409
#define INPUT_BUTTON_A						410
#define INPUT_BUTTON_B						411
#define INPUT_BUTTON_C						412
#define INPUT_BUTTON_D						413
#define INPUT_BUTTON_E						414
#define INPUT_BUTTON_F						415
#define INPUT_BUTTON_G						416
#define INPUT_BUTTON_H						417
#define INPUT_BUTTON_I						418
#define INPUT_BUTTON_J						419
#define INPUT_BUTTON_K						420
#define INPUT_BUTTON_L						421
#define INPUT_BUTTON_M						422
#define INPUT_BUTTON_N						423
#define INPUT_BUTTON_O						424
#define INPUT_BUTTON_P						425
#define INPUT_BUTTON_Q						426
#define INPUT_BUTTON_R						427
#define INPUT_BUTTON_S						428
#define INPUT_BUTTON_T						429
#define INPUT_BUTTON_U						430
#define INPUT_BUTTON_V						431
#define INPUT_BUTTON_W						432
#define INPUT_BUTTON_X						433
#define INPUT_BUTTON_Y						434
#define INPUT_BUTTON_Z						435
#define INPUT_BUTTON_DEL					450
#define INPUT_BUTTON_INS					451
#define INPUT_BUTTON_BACK					452
#define INPUT_BUTTON_BACKLINE				453
#define INPUT_BUTTON_INSLINE				454
#define INPUT_BUTTON_KEYOFF					455
#define INPUT_BUTTON_MINUS					457
#define INPUT_BUTTON_PLUS					458
#define INPUT_BUTTON_BRACKETOPEN			460
#define INPUT_BUTTON_BRACKETCLOSE			461
#define INPUT_BUTTON_SEMICOLON				462
#define INPUT_BUTTON_TICK					463
#define INPUT_BUTTON_BACKSLASH				464
#define INPUT_BUTTON_TILDE					465
#define INPUT_BUTTON_COMMA					466
#define INPUT_BUTTON_PERIOD					467
#define INPUT_BUTTON_SLASH					468
#define INPUT_BUTTON_TAB					470
#define INPUT_BUTTON_CAPSLOCK				471
#define INPUT_BUTTON_LSHIFT					472
#define INPUT_BUTTON_RSHIFT					473
#define INPUT_BUTTON_ENTER					474
#define INPUT_BUTTON_SPACE					475
#define INPUT_BUTTON_SHRINK					480
#define INPUT_BUTTON_EXPAND					481
#define INPUT_BUTTON_EDIT					490
#define INPUT_BUTTON_WTF					491

#define STATICTEXT_ENVELOPE_SUSTAINPT		10500
#define STATICTEXT_ENVELOPE_LOOPSTARTPT		10501
#define STATICTEXT_ENVELOPE_LOOPENDPT		10502

#define STATICTEXT_SAMPLE_VOLUME			10503
#define STATICTEXT_SAMPLE_PANNING			10504
#define STATICTEXT_SAMPLE_FINETUNE			10505
#define STATICTEXT_SAMPLE_RELNOTE			10506
#define STATICTEXT_SAMPLE_VOLFADE			10507
#define STATICTEXT_SAMPLE_VIBSPEED			10508
#define STATICTEXT_SAMPLE_VIBDEPTH			10509
#define STATICTEXT_SAMPLE_VIBSWEEP			10510

#define STATICTEXT_SAMPLE_LENGTH			10511
#define STATICTEXT_SAMPLE_DISPLAY			10512
#define STATICTEXT_SAMPLE_REPSTART			10513
#define STATICTEXT_SAMPLE_REPLENGTH			10514
#define STATICTEXT_SAMPLE_PLAYNOTE			10515

#define BUTTON_MENU_ITEM_0					530

#define BUTTON_MENU_ITEM_ADDCHANNELS		560
#define BUTTON_MENU_ITEM_SUBCHANNELS		561

#define BUTTON_ABOUT_SHOWTITLE				600
#define BUTTON_ABOUT_SHOWPEAK				601
#define BUTTON_ABOUT_SHOWTIME				602
#define BUTTON_ABOUT_FOLLOWSONG				603
#define BUTTON_ABOUT_PROSPECTIVE			604
#define BUTTON_ABOUT_WRAPCURSOR				605
#define STATICTEXT_ABOUT_HEADING			610
#define STATICTEXT_ABOUT_TIME				611
#define BUTTON_ABOUT_ESTIMATESONGLENGTH		612

#define BUTTON_TAB_CLOSE					613
#define BUTTON_TAB_OPEN						614

#define SCROLLBAR_0					1000

#define LISTBOX_0					2000
#define LISTBOX_ORDERLIST			2001
#define LISTBOX_INSTRUMENTS			2002
#define LISTBOX_SAMPLES				2003

#define CHECKBOX_0					2100

//#define CONTAINER_MARGIN			2999
#define CONTAINER_0					3000
#define CONTAINER_ORDERLIST			3001
#define CONTAINER_SPEED    			3002
#define CONTAINER_PATTERN			3003
#define CONTAINER_MENU				3004
#define CONTAINER_ABOUT				3005
#define CONTAINER_ENVELOPES			3006
#define CONTAINER_INSTRUMENTLIST	3007 // sample info
#define CONTAINER_INSTRUMENTS_INFO1	3008 // vibrato info
#define CONTAINER_INSTRUMENTS_INFO2	3009 // relative note number
#define CONTAINER_INSTRUMENTS_INFO3	3010
#define CONTAINER_INSTRUMENTS_INFO4	3011
#define CONTAINER_INSTRUMENTS_INFO5	3012
#define CONTAINER_INSTRUMENTS_INFO6	3013
#define CONTAINER_PIANO				3014
#define CONTAINER_SAMPLEEDITOR		3015
#define CONTAINER_SAMPLE_PLAY		3016
#define CONTAINER_SAMPLE_RANGE		3017
#define CONTAINER_SAMPLE_EDIT1		3018
#define CONTAINER_SAMPLE_EDIT2		3019
#define CONTAINER_SAMPLE_EDIT3		3020
#define CONTAINER_SAMPLE_EDIT4		3021
#define CONTAINER_SAMPLE_EDIT5		3022
#define CONTAINER_SAMPLE_LOADSAVE   3024
#define CONTAINER_SETTINGS_1		3025
#define CONTAINER_SETTINGS_2		3026
#define CONTAINER_SETTINGS_3		3027
#define CONTAINER_SETTINGS_4		3028
#define CONTAINER_SETTINGS_5		3029
#define CONTAINER_SETTINGS_6		3030
#define CONTAINER_SETTINGS_7		3031
#define CONTAINER_SETTINGS_8		3032
#define CONTAINER_TRANSPOSE			3040
#define CONTAINER_ADVEDIT			3041
#define CONTAINER_LOWRES_MENUSWITCH 3042
#define CONTAINER_LOWRES_TINYMENU   3043 // sample info
#define CONTAINER_LOWRES_JAMMENU	3044
#define CONTAINER_INPUTDEFAULT		3045
#define CONTAINER_INPUTEXTENDED		3046
#define CONTAINER_SAMPLE_ZOOMIN		3047
#define CONTAINER_HDRECORDER		3048
#define CONTAINER_OPENREMOVETABS	3049
#define CONTAINER_ENTIREINSSECTION	3050
#define CONTAINER_ENTIRESMPSECTION	3051

#define PATTERN_EDITOR				10000
#define PIANO_CONTROL				10001
#define SAMPLE_EDITOR				10002
#define PEAKLEVEL_CONTROL			10003
#define SCOPES_CONTROL				10004
#define TABHEADER_CONTROL			10005

#define MESSAGEBOXZAP_CONTAINER		20000
#define MESSAGEBOXZAP_BUTTON_ALL	20100
#define MESSAGEBOXZAP_BUTTON_SONG	20101
#define MESSAGEBOXZAP_BUTTON_PATT	20102
#define MESSAGEBOXZAP_BUTTON_INS	20103
//#define MESSAGEBOXZAP_BUTTON_CANCEL	20104

#define INSTRUMENT_CHOOSER_COPY			21000
#define INSTRUMENT_CHOOSER_SWAP			21001
#define INSTRUMENT_CHOOSER_LIST_SRC		21101
#define INSTRUMENT_CHOOSER_LIST_DST		21102
#define INSTRUMENT_CHOOSER_LIST_SRC2	21103
#define INSTRUMENT_CHOOSER_LIST_DST2	21104
#define INSTRUMENT_CHOOSER_LIST_SRC3	21105
#define INSTRUMENT_CHOOSER_LIST_DST3	21106
#define INSTRUMENT_CHOOSER_USERSTR1		21107
#define INSTRUMENT_CHOOSER_USERSTR2		21108

#define MESSAGEBOX_UNIVERSAL		29999
#define MESSAGEBOX_CONVERTSAMPLE	30000
#define MESSAGEBOX_CLEARSAMPLE		30001
#define MESSAGEBOX_MINIMISESAMPLE   30002
#define MESSAGEBOX_CROPSAMPLE		30003
#define MESSAGEBOX_INSREMAP			30004
#define MESSAGEBOX_ZAPINSTRUMENT	30005
#define MESSAGEBOX_REALLYQUIT		30006
#define MESSAGEBOX_TRANSPOSEPROCEED 30007
#define MESSAGEBOX_SAVEPROCEED		30008
#define MESSAGEBOX_PANNINGSELECT	30009

#endif
